import { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import { IApiApplyhomeInfoDetailSvcV1GetAPTLttotPblancMdl } from "../../../../structures/IApiApplyhomeInfoDetailSvcV1GetAPTLttotPblancMdl";
import { getAPTLttotPblancMdl_api } from "../../../../structures/getAPTLttotPblancMdl_api";
/**
 * APT 분양정보 주택형별 상세조회.
 * 주택관리번호, 공고번호 값을 이용하여 APT 분양정보 주택형별 상세정보를 제공
 *
 * 특별공급-청년, 신생아 세대수는 공공주택일 경우만 해당
 * (APT 분양정보 상세조회 서비스 내 HOUSE_DETAIL_SECD='03' & PUBLIC_HOUSE_SPCLW_APPLC_AT='Y'인 경우 공공주택에 해당)
 *
 * @security ApiKeyAuth
 * @security ApiKeyAuth2
 * @tag API 목록
 * @path ApplyhomeInfoDetailSvc/v1/getAPTLttotPblancMdl
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
  connection: IConnection,
  query: get.Query,
): Promise<get.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...get.METADATA,
      path: get.path(query),
      status: null,
    },
  );
}
export namespace get {
  export type Query = IApiApplyhomeInfoDetailSvcV1GetAPTLttotPblancMdl.GetQuery;
  export type Output = getAPTLttotPblancMdl_api;

  export const METADATA = {
    method: "GET",
    path: "/ApplyhomeInfoDetailSvc/v1/getAPTLttotPblancMdl",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (query: get.Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/ApplyhomeInfoDetailSvc/v1/getAPTLttotPblancMdl";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
